# fly.toml app configuration file generated for withered-leaf-6340 on 2023-09-12T22:21:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "withered-leaf-6340"
console_command = "/code/WebAppTeam4/manage.py shell"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "yul"
processes = []

[build]

[deploy]
  release_command = "python /code/WebAppTeam4/manage.py migrate"

[env]
  PORT = "8000"
SECRET_KEY="django-insecure-4u10lnpkw-h(xg@u7k+g2(-7%)19=54ee@(z)7qlsj&hl^-&xa"
EMAIL_HOST_USER="email-robot@meta.ua"
EMAIL_HOST_PASSWORD="Robot_159357!"
EMAIL_HOST="smtp.meta.ua"
EMAIL_PORT="465"
DATABASE_NAME="Dj_proj_team4"
DATABASE_USER="postgres"
DATABASE_PASSWORD="567234"
DATABASE_HOST="195.201.150.230"
DATABASE_PORT="5433"
DROP_BOX="sl.Bl1BH2jTejjBJ6Yymaf-uItrpGlhmaO4jh0ylTc80Q5FREPWJj8sndTgMNSwnhKStuwoai6ivFXhjXMXI6UYqay84OqELEjgW0zTgV44gx4_U8kzpMw4UNNln2z7r2ZUPyAo4_ABQjibRRPyXVZs"
DROPBOX_APP_KEY="1xbrg9md2qemzlk"
DROPBOX_APP_SECRET="orsh6t9q4ln6kje"
REDIS="redis"
REDIS_HOST="195.201.150.230"
REDIS_PASSWORD="567234"
REDIS_PORT="6379"
REDIS_DB="db0"
WEATHER_API_KEY="3478743f8ff6ad5d9cae9ea84b3cb414"
USER_AGENT="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
CSRF_TRUSTED_ORIGINS="https://withered-leaf-6340.fly.dev"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

